// <auto-generated />
namespace app.master.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class AlterProductTableSetBoolTypeAndObservationValues : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlterProductTableSetBoolTypeAndObservationValues));
        
        string IMigrationMetadata.Id
        {
            get { return "202002242121221_AlterProductTableSetBoolTypeAndObservationValues"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
